### ISSUE TITLE
Response timeout

### ISSUE THREAD

**Issue by Avey777** [spywiree/translateimage#3] opened 2024-04-29 04:36 UTC
```
(base) root@Jengro:~# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
(base) root@Jengro:~# 
```

I can access Google normally, but running main.go keeps timeout

```
(base) root@Jengro:/home/jengro/dev/translateimage# go run example/main.go 
2024/04/29 12:34:19 playwright: timeout: Timeout 30000ms exceeded.
exit status 1
```

**Comment by Avey777** [comment] 2024-05-04 06:37
No matter how long the timeout is set, running main.go still prompts for timeout. So far, I haven't succeeded once

**Comment by spywiree-priv** [comment] 2024-05-04 16:23
I can't reproduce this problem unless I slow down my internet very much. So, send me your ping, internet speed and full console output from the example in the dev branch.

**Comment by Avey777** [comment] 2024-05-10 06:24
```
PS C:\Users\Administrator\Documents\Dev\translateimage> ping translate.google.pl

Pinging translate.google.pl [216.58.223.195] with 32 bytes of data:
Reply from 216.58.223.195: bytes=32 time=14ms TTL=118
Reply from 216.58.223.195: bytes=32 time=14ms TTL=118
Reply from 216.58.223.195: bytes=32 time=14ms TTL=118
Reply from 216.58.223.195: bytes=32 time=14ms TTL=118

Ping statistics for 216.58.223.195:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 14ms, Maximum = 14ms, Average = 14ms
PS C:\Users\Administrator\Documents\Dev\translateimage>



PS C:\Users\Administrator\Documents\Dev\translateimage> git branch
* dev
  main
PS C:\Users\Administrator\Documents\Dev\translateimage> go run .\example\main.go
2024/05/10 06:21:32 Driver and Firefox browser installed
2024/05/10 06:21:33 Playwright instance started
2024/05/10 06:21:33 Firefox instance started
2024/05/10 06:21:34 Created a new page
2024/05/10 06:21:35 Set the site URL to: https://translate.google.pl/?op=images&hl=en&sl=auto&tl=en
2024/05/10 06:22:06 playwright: timeout: Timeout 30000ms exceeded.
exit status 1
PS C:\Users\Administrator\Documents\Dev\translateimage>
```

**Comment by spywiree-priv** [comment] 2024-05-10 18:58
I have written a draft patch. Please test it and send me the console results and the videos.zip file.

**Comment by Avey777** [comment] 2024-05-11 08:12
> I have written a draft patch. Please test it and send me the console output and the videos.zip file.

https://tmp.link/f/663f285402799

**Comment by spywiree-priv** [comment] 2024-05-11 18:48
I didn't mean the screen recording, but the videos.zip file, which contains recordings of the headless browser. After running these commands:

    git clone https://github.com/spywiree/translateimage.git
    cd translateimage
    git checkout dev
    cd example
    go run .

the videos.zip file will be in the translateimage/example folder.

**Comment by Avey777** [comment] 2024-05-12 01:13
> 我指的不是屏幕录制，而是 videos.zip 文件，其中包含无头浏览器的录制。运行以下命令后：
> 
> ```
> git clone https://github.com/spywiree/translateimage.git
> cd translateimage
> git checkout dev
> cd example
> go run .
> ```
> 
> videos.zip文件将位于 TranslateImage/Example 文件夹中。

[videos.zip](https://github.com/spywiree/translateimage/files/15284734/videos.zip)

**Comment by Avey777** [comment] 2024-05-15 05:52
@spywiree-priv  Found a solution?

**Comment by spywiree-priv** [comment] 2024-05-15 15:35
I think so. Check now.

**Comment by Avey777** [comment] 2024-05-16 09:13
> I think so. Check now.

Great, it can work now

**Closed** 2024-05-16 10:42 UTC
